package edu.grinnell.csc207.soundsofsorting.sorts;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;

import edu.grinnell.csc207.soundsofsorting.sortevents.CompareEvent;
import edu.grinnell.csc207.soundsofsorting.sortevents.CopyEvent;
import edu.grinnell.csc207.soundsofsorting.sortevents.SortEvent;
import edu.grinnell.csc207.soundsofsorting.sortevents.SwapEvent;

/**
 * A collection of sorting algorithms.
 */
public class Sorts {

    /**
     * Swaps indices <code>i</code> and <code>j</code> of array <code>arr</code>.
     * @param <T> the carrier type of the array
     * @param arr the array to swap
     * @param i the first index to swap
     * @param j the second index to swap
     */
    public static <T> void swap(T[] arr, int i, int j) {
        T tmp = arr[i];
        arr[i] = arr[j];
        arr[j] = tmp;
    }

    /**
     * Sorts the array according to the bubble sort algorithm:
     * <pre>
     * [ unprocessed | i largest elements in order ]
     * </pre>
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<Integer>> bubbleSort(T[] arr) {
       
        
        List<SortEvent<Integer>> events = new ArrayList<SortEvent<Integer>>();

        for(int i = arr.length-1; i >= 0; i--){
            for(int j = arr.length-1; j >= 0; j--){

                List<Integer> compareIndices = new ArrayList<>();
                compareIndices.add(i);
                compareIndices.add(j);
                CompareEvent<Integer> compares = new CompareEvent<>(compareIndices);
                events.add(compares);

                if(arr[i].compareTo(arr[j]) > 0){
                    swap(arr, i, j);
                    List<Integer> swapIndices = new ArrayList<>();
                    swapIndices.add(i);
                    swapIndices.add(j);
                    SwapEvent<Integer> swaps = new SwapEvent<>(swapIndices);
                    events.add(swaps);
                }
            }
        }
        return events;
    }

    /**
     * Sorts the array according to the selection sort algorithm:
     * <pre>
     * [ i smallest elements in order | unprocessed ]
     * </pre>
     * 
     *  <- original return type
     * 
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<Integer>> selectionSort(T[] arr) {
        int min = 0;
        List<SortEvent<Integer>> events = new ArrayList<SortEvent<Integer>>();
        for(int i = 0; i < arr.length; i++){
            for(int j = i; j < arr.length; j++){

                List<Integer> compareIndices = new ArrayList<>();
                compareIndices.add(min);
                compareIndices.add(j);
                CompareEvent<Integer> compares = new CompareEvent<>(compareIndices);
                events.add(compares);

                if(arr[min].compareTo(arr[j]) > 0){
                    min = j;
                }
            }
            swap(arr, i, min);
            List<Integer> swapIndices = new ArrayList<>();
            swapIndices.add(i);
            swapIndices.add(min);
            SwapEvent<Integer> swaps = new SwapEvent<>(swapIndices);
            events.add(swaps);
            min = i+1;
        }

        return events;
    }

    /**
     * Sorts the array according to the insertion sort algorithm:
     * <pre>
     * [ i elements in order | unprocessed ] 
     * </pre>
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<Integer>> insertionSort(T[] arr) {
        List<SortEvent<Integer>> events = new ArrayList<SortEvent<Integer>>();

        for(int i = 0; i < arr.length; i++){
            for(int j = 0; j < arr.length; j++){
                List<Integer> compareIndices = new ArrayList<>();
                compareIndices.add(i);
                compareIndices.add(j);
                CompareEvent<Integer> compares = new CompareEvent<>(compareIndices);
                events.add(compares);
                if(arr[i].compareTo(arr[j]) < 0){
                    List<Integer> swapIndices = new ArrayList<>();
                    swapIndices.add(i);
                    swapIndices.add(j);
                    SwapEvent<Integer> swaps = new SwapEvent<>(swapIndices);
                    events.add(swaps);
                    swap(arr, i, j);
                }
            }

        }
        return events;
    }

    /**
     * Sorts the array according to the merge sort algorithm.
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<Integer>> mergeSort(T[] arr) {
        List<SortEvent<Integer>> events = new ArrayList<SortEvent<Integer>>();

        if (arr == null || arr.length <= 1) {
            return null;
        }

        T[] new_arr = java.util.Arrays.copyOf(arr, arr.length);

        mergeHelper(arr, new_arr, 0, arr.length-1, events);
        return events;
    }

    public static <T extends Comparable<? super T>> void mergeHelper(T[] arr, T[] new_arr, int fst, int lst, List<SortEvent<Integer>> events) {
        if (fst >= lst){
            return;
        } 

        int mid = (fst + lst) / 2;

        mergeHelper(arr, new_arr, fst, mid, events);
        mergeHelper(arr, new_arr, mid+1, lst, events);
        sortHelper(arr, new_arr, fst, mid, lst, events);
    }

    public static <T extends Comparable<? super T>> List<SortEvent<Integer>> sortHelper(T[] arr, T[] new_arr, int fst, int mid, int lst, List<SortEvent<Integer>> events) {
        int cur1 = fst;
        int cur2 = mid + 1;
        int newcur = fst;

        if (newcur == lst) {
            return events;
        }
        
        while((cur1 <= mid) && (cur2 <= lst)) {

            List<Integer> compareIndices = new ArrayList<>();
            compareIndices.add(cur1);
            compareIndices.add(cur2);
            CompareEvent<Integer> compares = new CompareEvent<>(compareIndices);
            events.add(compares);

            if (arr[cur1].compareTo(arr[cur2]) < 0) {
                List<Integer> copyIndices = new ArrayList<>();
                copyIndices.add(newcur);
                T val = arr[cur1];
                CopyEvent<Integer> copies = new CopyEvent<Integer>((int)val, copyIndices);
                events.add(copies);
                new_arr[newcur++] = arr[cur1++];
            } else {
                new_arr[newcur++] = arr[cur2++];
            } 
        }

        // catch cursors up after 1 half is fully sorted
        while (cur1 <= mid) {
            new_arr[newcur++] = arr[cur1++];
        }
        while (cur2 <= lst) {
            new_arr[newcur++] = arr[cur2++];
        }

        // write back to old array
        System.arraycopy(new_arr, fst, arr, fst, lst-fst+1);
        return null;
    }


    /**
     * Sorts the array according to the quick sort algorithm.
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<Integer>> quickSort(T[] arr) {
        List<SortEvent<Integer>> events = new ArrayList<SortEvent<Integer>>();
        quickSortHelper(arr, 0, arr.length - 1, events);
        return events;
    }

    public static <T extends Comparable<? super T>> List<SortEvent<Integer>> quickSortHelper(T[] arr, int cur1, int cur2, List<SortEvent<Integer>> events) {
        if (cur1 >= cur2){
            return events;
        } 

        int c1 = cur1;
        int c2 = cur2 - 1;

        Random rand = new Random();
        int part = rand.nextInt(cur1, cur2 + 1);

        List<Integer> swapIndices = new ArrayList<>();
        swapIndices.add(part);
        swapIndices.add(cur2);
        SwapEvent<Integer> swaps = new SwapEvent<>(swapIndices);
        events.add(swaps);
        swap(arr, part, cur2);

        while (c1 <= c2) {
            List<Integer> compareIndices = new ArrayList<>();
            compareIndices.add(c1);
            compareIndices.add(cur2);
            CompareEvent<Integer> compares = new CompareEvent<>(compareIndices);
            events.add(compares);
            if (arr[c1].compareTo(arr[cur2]) <= 0) {
                c1++;
            } else {
                List<Integer> swapIndices2 = new ArrayList<>();
                swapIndices2.add(c1);
                swapIndices2.add(c2);
                SwapEvent<Integer> swaps2 = new SwapEvent<>(swapIndices);
                events.add(swaps2);
                swap(arr, c1, c2);
                c2--;
            }
        }

        List<Integer> swapIndices3 = new ArrayList<>();
        swapIndices3.add(c1);
        swapIndices3.add(cur2);
        SwapEvent<Integer> swaps3 = new SwapEvent<>(swapIndices);
        events.add(swaps3);
        swap(arr, c1, cur2);  // place pivot in back

        // recurse on both sides
        quickSortHelper(arr, cur1, c1 - 1, events);
        quickSortHelper(arr, c1 + 1, cur2, events);
        return null;
    }


    /**
     * Sorts the array according to the exchange sort algorithm.
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    
    public static <T extends Comparable<? super T>> List<SortEvent<Integer>> exchangeSort(T[] arr){
        //List<Integer> compareIndices = new ArrayList<>();
        //List<Integer> swapIndices = new ArrayList<>();
        //CompareEvent<Integer> compares = new CompareEvent<>(compareIndices);
        //SwapEvent<Integer> swaps = new SwapEvent<>(swapIndices);
        List<SortEvent<Integer>> events = new ArrayList<SortEvent<Integer>>();
        
        for(int i = 0; i < arr.length; i++){
            for(int j = i; j < arr.length; j++){
                if(arr[i].compareTo(arr[j]) > 0){

                    List<Integer> compareIndices = new ArrayList<>();
                    compareIndices.add(i);
                    compareIndices.add(j);
                    CompareEvent<Integer> compares = new CompareEvent<>(compareIndices);

                    swap(arr, i, j);

                    List<Integer> swapIndices = new ArrayList<>();
                    swapIndices.add(i);
                    swapIndices.add(j);
                    SwapEvent<Integer> swaps = new SwapEvent<>(swapIndices);
                    
                    events.add(compares);
                    events.add(swaps);
                }
            }   
        }

        return events;
    }
    /**
     * given an array of Ts and list of SortEvent<T> objects, the function will apply those 
     * events to the list in-order
     * @param <T> the carrier type of the array
     * @param l : an array of <T>s
     * @param events : A list of SortEvent objects
     */
    public static <T> void eventSort(T[] l, List<SortEvent<T>> events){
        for(SortEvent<T> event: events){
            event.apply(l);
        }
    }
}
