package edu.grinnell.csc207.soundsofsorting.sorts;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;

import edu.grinnell.csc207.soundsofsorting.sortevents.CompareEvent;
import edu.grinnell.csc207.soundsofsorting.sortevents.CopyEvent;
import edu.grinnell.csc207.soundsofsorting.sortevents.SortEvent;
import edu.grinnell.csc207.soundsofsorting.sortevents.SwapEvent;

/**
 * A collection of sorting algorithms.
 */
public class Sorts {

    /**
     * Swaps indices <code>i</code> and <code>j</code> of array <code>arr</code>.
     * @param <T> the carrier type of the array
     * @param arr the array to swap
     * @param i the first index to swap
     * @param j the second index to swap
     */
    public static <T> void swap(T[] arr, int i, int j) {
        T tmp = arr[i];
        arr[i] = arr[j];
        arr[j] = tmp;
    }

    /**
     * Sorts the array according to the bubble sort algorithm:
     * <pre>
     * [ unprocessed | i largest elements in order ]
     * </pre>
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<Integer>> bubbleSort(T[] arr) {
        for(int i = arr.length-1; i >= 0; i--){
            for(int j = arr.length-1; j >= 0; j--){
                if(arr[i].compareTo(arr[j]) > 0){
                    swap(arr, i, j);
                }
            }
        }
        return null;
    }

    /**
     * Sorts the array according to the selection sort algorithm:
     * <pre>
     * [ i smallest elements in order | unprocessed ]
     * </pre>
     * 
     *  <- original return type
     * 
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<Integer>> selectionSort(T[] arr) {
        int min = 0;
        for(int i = 0; i < arr.length; i++){
            for(int j = i; j < arr.length; j++){
                if(arr[min].compareTo(arr[j]) > 0){
                    min = j;
                }
            }
            swap(arr, i, min);
            min = i+1;
        }

        return null;
    }

    /**
     * Sorts the array according to the insertion sort algorithm:
     * <pre>
     * [ i elements in order | unprocessed ] 
     * </pre>
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<Integer>> insertionSort(T[] arr) {
        for(int i = 0; i < arr.length; i++){
            for(int j = 0; j < arr.length; j++){
                if(arr[i].compareTo(arr[j]) < 0){
                    swap(arr, i, j);
                }
            }

        }
        return null;
    }

    /**
     * Sorts the array according to the merge sort algorithm.
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<Integer>> mergeSort(T[] arr) {

        if (arr == null || arr.length <= 1) {
            return null;
        }

        T[] new_arr = java.util.Arrays.copyOf(arr, arr.length);

        mergeHelper(arr, new_arr, 0, arr.length-1);
        return null;
    }

    public static <T extends Comparable<? super T>> void mergeHelper(T[] arr, T[] new_arr, int fst, int lst) {
        if (fst >= lst){
            return;
        } 

        int mid = (fst + lst) / 2;

        mergeHelper(arr, new_arr, fst, mid);
        mergeHelper(arr, new_arr, mid+1, lst);
        sortHelper(arr, new_arr, fst, mid, lst);
    }

    public static <T extends Comparable<? super T>> void sortHelper(T[] arr, T[] new_arr, int fst, int mid, int lst) {
        int cur1 = fst;
        int cur2 = mid + 1;
        int newcur = fst;

        if (newcur == lst) return;

        while((cur1 <= mid) && (cur2 <= lst)) {
            if (arr[cur1].compareTo(arr[cur2]) < 0) {
                new_arr[newcur++] = arr[cur1++];
            } else {
                new_arr[newcur++] = arr[cur2++];
            } 
        }

        // catch cursors up after 1 half is fully sorted
        while (cur1 <= mid) {
            new_arr[newcur++] = arr[cur1++];
        }
        while (cur2 <= lst) {
            new_arr[newcur++] = arr[cur2++];
        }

        // write back to old array
        System.arraycopy(new_arr, fst, arr, fst, lst-fst+1);
    }


    /**
     * Sorts the array according to the quick sort algorithm.
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<Integer>> quickSort(T[] arr) {
        CompareEvent<Integer> compares = null;
        SwapEvent<Integer> swaps = null;
        CopyEvent<Integer> copies = null;
        List<SortEvent<Integer>> events = new ArrayList<SortEvent<Integer>>();
        events.add(compares);
        events.add(copies);
        events.add(swaps);
         quickSortHelper(arr, 0, arr.length - 1);
        return null;
    }

    public static <T extends Comparable<? super T>> void quickSortHelper(T[] arr, int cur1, int cur2) {
        if (cur1 >= cur2){
            return;
        } 

        int c1 = cur1;
        int c2 = cur2 - 1;

        Random rand = new Random();
        int part = rand.nextInt(cur1, cur2 + 1);

        swap(arr, part, cur2);

        while (c1 <= c2) {
            if (arr[c1].compareTo(arr[cur2]) <= 0) {
                c1++;
            } else {
                swap(arr, c1, c2);
                c2--;
            }
        }

        swap(arr, c1, cur2);  // place pivot in back

        // recurse on both sides
        quickSortHelper(arr, cur1, c1 - 1);
        quickSortHelper(arr, c1 + 1, cur2);
    }


    /**
     * Sorts the array according to the exchange sort algorithm.
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    
    public static <T extends Comparable<? super T>> List<SortEvent<Integer>> exchangeSort(T[] arr){
        CompareEvent<Integer> compares = new CompareEvent<>();
        SwapEvent<Integer> swaps = new SwapEvent<>();
        CopyEvent<Integer> copies = new CopyEvent<>();
        List<SortEvent<Integer>> events = new ArrayList<SortEvent<Integer>>();
        events.add(compares);
        events.add(copies);
        events.add(swaps);
        for(int i = 0; i < arr.length; i++){
            for(int j = i; j < arr.length; j++){
                if(arr[i].compareTo(arr[j]) > 0){
                    compares.indices.add(i);
                    compares.indices.add(j);
   
                    swap(arr, i, j);

                    copies.indices.add(i);
                    copies.indices.add(j);

                    swaps.indices.add(i);
                    swaps.indices.add(j);
                }
            }   
        }
        return events;
    }
    /**
     * given an array of Ts and list of SortEvent<T> objects, the function will apply those 
     * events to the list in-order
     * @param <T> the carrier type of the array
     * @param l : an array of <T>s
     * @param events : A list of SortEvent objects
     */
    public static <T> void eventSort(T[] l, List<SortEvent<T>> events){
            events.get(0).apply(l);
            events.get(1).apply(l);
            events.get(2).apply(l);
    }
}
